### PR TITLE
A bunch of changes (test me please)

### PR DESCRIPTION
**Pull request by easyaspi314**
<h4>Added:</h4>
* Eclipse compatibility (I think)
* PreferenceFragment using an extension of the Support Library
* Fixed a VerifyError crash when testing on my Donut emulator on getActionBar()
* Richer About screen 
 - Uses string-arrays to inflate a PreferenceFragment, There are some sets of string-arrays that contain usernames and real names. A for loop adds a Preference to the fragment and sets it so when you click it, it goes to github.com/their-username. If you want
* Preferences - removed unnecessary OnPreferenceClickListeners
 - Custom EditTextPreference that adds a new Subject
* Switched to FragmentActivity to make some use of the Support Library.

*There are a million commits because I did not want to update to the new structure. I edited them in the web editor, so please test this. I am stuck on Eclipse because Android Studio refuses to start on my computer.*. :weary:

### CODE REVIEW

**Comment by AltNico** [comment]
Hi, thanks for your work, the code looks fine, but when I opened Android Studio, this error appeared:
Error:Failed to find: com.android.support:support-v4-preferencefragment:1.0.0
It's crazy, because AS also makes a new module (app-app) when I open it.

So I only merged until 0a50c4eb0778c5c39bf24ce0e579b86598f862fa (Eclipse compatibility), I'll try to add the other stuff manually.

**Comment by easyaspi314** [comment]
Yes you need to add the m2repository from
https://github.com/kolovar/android-support-v4-preferencefragment/ it is a
great unofficial extension to the Support Library that adds the
PreferenceFragment class, strangely missing from the v4 lib.

**Comment by AltNico** [comment]
I'll wait for https://github.com/kolavar/android-support-v4-preferencefragment/issues/13 to be solved before I add the libary -> merge the request.

**Comment by easyaspi314** [comment]
I have added you as a collaborator to my fork in case you want to make any
changes.

**Comment by easyaspi314** [comment]
I fixed the dependency issue by adding it as a submodule.

**Comment by AltNico** [comment]
Sorry man, but I can not merge this, the changes are too large and it's not suitable to work with Eclipse since the whole structure is changed.
I know, the old project's IDE was Eclipse, but since Google released AS 1.0 and said, ADT isn't supported anymore, I wanted to be on the safe side and switched to Android Studio.
Sorry for this, but I'll delete the Eclipse files and close this request...

**Comment by easyaspi314** [comment]
It's alright. Those changes were mainly for me, as like I said, AS does not
work for me. I might try AS again, but thanks anyway.

**Pull request closed without merging**
